---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: archive
  namespace: pipeline-musr
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=2.1
    - noserverino
    - _netdev
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: archive-01  # make sure this value is unique for every connection from the cluster
    volumeAttributes:
      source: "//ISISARVR55.isis.cclrc.ac.uk/SuperMusrTestDataBackup$"
    nodeStageSecretRef:
      name: archive-creds
      namespace: pipeline-musr

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: archive
  namespace: pipeline-musr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: archive
  storageClassName: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: archive-creds
  namespace: pipeline-musr
type: Opaque
stringData:
  username: SuperMusr_mgr
  password: ""
  domain: ISIS
