alertmanager:
  enabled: false

prometheus-node-exporter:
  enabled: true

prometheus-pushgateway:
  enabled: false

server:
  extraFlags:
    - web.enable-lifecycle
    - web.enable-remote-write-receiver

  persistentVolume:
    enabled: true
    size: 10Gi
